import { useQuery } from '@tanstack/react-query';
import { searchInventories } from '../services/searchInventories.api';

export const useSearchInventories = ({
  searchTerm,
  deadlineId,
  projectId,
  purchaseOrderId,
  invoiceId,
  verticalId,
  locationName,
  sortBy,
  order,
  page,
  pageSize,
  conditionName,
  deepSearch,
  status,
  advancedSearch = 'true',
  signal,
}) => {
  return useQuery({
    queryKey: [
      'search-inventories',
      searchTerm,
      deadlineId,
      projectId,
      purchaseOrderId,
      invoiceId,
      verticalId,
      locationName,
      sortBy,
      order,
      page,
      pageSize,
      conditionName,
      deepSearch,
      status,
      advancedSearch,
    ],
    queryFn: () =>
      searchInventories({
        searchTerm,
        deadlineId,
        projectId,
        purchaseOrderId,
        invoiceId,
        verticalId,
        locationName,
        sortBy,
        order,
        page,
        pageSize,
        conditionName,
        deepSearch,
        status,
        advancedSearch,
        signal,
      }),
    enabled: true,
    keepPreviousData: true,
    refetchOnWindowFocus: false,
  });
};
