export const vehicleColumns = [
  {
    id: 'checkbox',
    value: '',
    classes: 'w-20',
  },
  {
    id: 'images',
    value: 'Imagen',
    classes: 'w-20',
  },
  {
    id: 'model.name',
    value: 'Nombre',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'model.type.name',
    value: 'Tipo',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'model.brand.name',
    value: 'Marca',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'model.year',
    value: 'Año del modelo',
    classes: 'w-auto',
    order: 'asc',
    type: 'number',
  },
  {
    id: 'economicNumber',
    value: 'Número económico',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'serialNumber',
    value: 'Número de serie',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'plateNumber',
    value: 'Número de placa',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'acquisitionDate',
    value: 'Fecha de adquisición',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'cost',
    value: 'Costo de adquisición',
    classes: 'w-auto',
    order: 'asc',
    type: 'number',
  },
  {
    id: 'status',
    value: 'Estatus',
    classes: 'w-fit',
    order: 'asc',
  },
  {
    id: 'actions',
    value: 'Acciones',
    classes: 'text-center w-1',
  },
];
