import { createContext, useContext } from 'react';

const VehicleContext = createContext({
  vehicles: [],
  vehicle: {},
  vehicleTypes: [],
  vehicleType: {},
  vehicleBrands: [],
  vehicleBrand: {},
  vehicleModels: [],
  vehicleModel: {},
  vehicleConditions: [],
  vehicleCondition: {},
  loading: true,
  fetchVehicles: async () => {},
  fetchVehicle: async () => {},
  createVehicle: async () => {},
  updateVehicle: async () => {},
  deleteVehicle: async () => {},
  fetchVehicleTypes: async () => {},
  fetchVehicleType: async () => {},
  createVehicleType: async () => {},
  updateVehicleType: async () => {},
  deleteVehicleType: async () => {},
  fetchVehicleBrands: async () => {},
  fetchVehicleBrand: async () => {},
  createVehicleBrand: async () => {},
  updateVehicleBrand: async () => {},
  deleteVehicleBrand: async () => {},
  fetchVehicleModels: async () => {},
  fetchVehicleModel: async () => {},
  createVehicleModel: async () => {},
  updateVehicleModel: async () => {},
  deleteVehicleModel: async () => {},
  fetchVehicleConditions: async () => {},
  fetchVehicleCondition: async () => {},
  createVehicleCondition: async () => {},
  updateVehicleCondition: async () => {},
  deleteVehicleCondition: async () => {},
});
export const useVehicleContext = () => useContext(VehicleContext);

export default VehicleContext;
