export const inventoryColumns = [
  {
    id: 'checkbox',
    value: '',
    classes: 'w-20',
  },
  {
    id: 'images',
    value: 'Imagen',
    classes: 'w-20',
  },
  {
    id: 'model.name',
    value: 'Modelo',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'model.type.name',
    value: 'Tipo',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'model.brand.name',
    value: 'Marca',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'serialNumber',
    value: 'Número de serie',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'activeNumber',
    value: 'Número de activo',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'comments',
    value: 'Comentarios',
    classes: 'w-24',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'receptionDate',
    value: 'F. Recepción',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'createdAt',
    value: 'F. Creación',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'updatedAt',
    value: 'F. Actualización',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'status',
    value: 'Estatus',
    classes: 'w-fit',
    order: 'asc',
  },
  {
    id: 'files',
    value: 'Archivos',
    classes: 'w-20',
    type: 'text',
  },
  {
    id: 'actions',
    value: 'Acciones',
    classes: 'text-center w-1',
  },
];
